In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn

%matplotlib inline

##### np.stack vs. np.concatenate

In [6]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])

print(a)
print()
print(b)
print()
print(c)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 9 10]
 [11 12]]


In [9]:
abc_concat_0 = np.concatenate((a, b,c), axis=0)
abc_stack_0 = np.stack((a, b, c), axis=0)

print(f"abc_concatenate_0의 shape : {abc_concat_0.shape}")
print(abc_concat_0)
print()
print(f"abc_stack_0의 shape : {abc_stack_0.shape}")
print(abc_stack_0)

abc_concatenate_0의 shape : (6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

abc_stack_0의 shape : (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [10]:
abc_concat_1 = np.concatenate((a, b, c), axis=1)
abc_stack_1 = np.stack((a, b, c), axis=1)

print(f"abc_concat_1의 shape : {abc_concat_1.shape}")
print(abc_concat_1)
print()
print(f"abc_stack_1의 shape : {abc_stack_1.shape}")
print(abc_stack_1)

abc_concat_1의 shape : (2, 6)
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]

abc_stack_1의 shape : (2, 3, 2)
[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]


##### np.concatenate는 서로 다른 차원의 array들끼리 합치는게 가능하지만 np.stack은 서로 차원이 다른 배열끼리는 합쳐지지 않습니다.

In [12]:
d = np.array([[13,14],[15,16],[17,18]])

print(f"d의 shape : {d.shape}")
print(d)

d의 shape : (3, 2)
[[13 14]
 [15 16]
 [17 18]]


In [14]:
abcd_concat_0 = np.concatenate((a,b,c,d), axis=0)

print(f"abcd_concat_0의 shape : {abcd_concat_0.shape}")
print(abcd_concat_0)

abcd_concat_1 = np.concatenate((a,b,c,d), axis=1)

abcd_concat_0의 shape : (9, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 3 has size 3

In [16]:
price = np.array([12,23,10,9])
maint = np.array([0,3,1,2])
doors = np.array([2,4,4,2])
person = np.array([2,4,1,3])
lug_capacity = np.array([2,3,2,2])
safety = np.array([1,0,0,1])

car_stack_1 = np.stack((price,maint,doors,person,lug_capacity,safety), axis=1)

print(f"car_stack_1의 shape : {car_stack_1.shape}")
print(car_stack_1)

car_stack_1의 shape : (4, 6)
[[12  0  2  2  2  1]
 [23  3  4  4  3  0]
 [10  1  4  1  2  0]
 [ 9  2  2  3  2  1]]
