In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn

%matplotlib inline

##### np.stack vs. np.concatenate

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])

print(a)
print()
print(b)


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [4]:
ab_concat_0 = np.concatenate((a, b), axis=0)
ab_stack_0 = np.stack((a, b), axis=0)

print(f"ab_concatenate_0의 shape : {ab_concat_0.shape}")
print(ab_concat_0)
print()
print(f"ab_stack_0의 shape : {ab_stack_0.shape}")
print(ab_stack_0)

ab_concatenate_0의 shape : (4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

ab_stack_0의 shape : (2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
ab_concat_1 = np.concatenate((a, b), axis=1)
ab_stack_1 = np.stack((a, b), axis=1)

print(f"ab_concat_1의 shape : {ab_concat_1.shape}")
print(ab_concat_1)
print()
print(f"ab_stack_1의 shape : {ab_stack_1.shape}")
print(ab_stack_1)

ab_concat_1의 shape : (2, 4)
[[1 2 5 6]
 [3 4 7 8]]

ab_stack_1의 shape : (2, 2, 2)
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
