In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn

%matplotlib inline

##### np.stack vs. np.concatenate

In [6]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])

print(a)
print()
print(b)
print()
print(c)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 9 10]
 [11 12]]


In [9]:
abc_concat_0 = np.concatenate((a, b,c), axis=0)
abc_stack_0 = np.stack((a, b, c), axis=0)

print(f"abc_concatenate_0의 shape : {abc_concat_0.shape}")
print(abc_concat_0)
print()
print(f"abc_stack_0의 shape : {abc_stack_0.shape}")
print(abc_stack_0)

abc_concatenate_0의 shape : (6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

abc_stack_0의 shape : (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [10]:
abc_concat_1 = np.concatenate((a, b, c), axis=1)
abc_stack_1 = np.stack((a, b, c), axis=1)

print(f"abc_concat_1의 shape : {abc_concat_1.shape}")
print(abc_concat_1)
print()
print(f"abc_stack_1의 shape : {abc_stack_1.shape}")
print(abc_stack_1)

abc_concat_1의 shape : (2, 6)
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]

abc_stack_1의 shape : (2, 3, 2)
[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]
