##### 가장 기초적인 방법의 선형회귀

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 재사용을 위해 랜덤값을 초기화합니다.
torch.manual_seed(2023)    

In [65]:
x_train = torch.FloatTensor([[1,3],[2,6],[3,9]])
y_train = torch.FloatTensor([[3],[6],[9]])

In [66]:
W = torch.zeros(size=(2,1), requires_grad=True)
b = torch.zeros(size=(1,), requires_grad=True)
W, b

(tensor([[0.],
         [0.]], requires_grad=True),
 tensor([0.], requires_grad=True))

In [67]:
hypothesis = torch.matmul(x_train, W) + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [68]:
cost = torch.mean((hypothesis - y_train) ** 2)
optimizer = optim.SGD([W, b], lr=0.01)

In [69]:
nb_epochs = 1000
for epoch in range(nb_epochs+1):
    hypothesis = torch.matmul(x_train, W) + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # cost로 H(x)개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그출력
    if not (epoch % 100):
        print(f"Epoch:{epoch:4d},  Cost:{cost.item():9.6f},  W_0:{W[0].item():.3f},  W_1:{W[1].item():.3f},  b:{b.item():.3f}")

Epoch:   0,  Cost:42.000000,  W_0:0.280,  W_1:0.840,  b:0.120
Epoch: 100,  Cost: 0.001306,  W_0:0.296,  W_1:0.888,  b:0.095
Epoch: 200,  Cost: 0.000745,  W_0:0.297,  W_1:0.891,  b:0.072
Epoch: 300,  Cost: 0.000424,  W_0:0.298,  W_1:0.893,  b:0.054
Epoch: 400,  Cost: 0.000242,  W_0:0.298,  W_1:0.895,  b:0.041
Epoch: 500,  Cost: 0.000138,  W_0:0.299,  W_1:0.896,  b:0.031
Epoch: 600,  Cost: 0.000079,  W_0:0.299,  W_1:0.897,  b:0.023
Epoch: 700,  Cost: 0.000045,  W_0:0.299,  W_1:0.898,  b:0.018
Epoch: 800,  Cost: 0.000026,  W_0:0.299,  W_1:0.898,  b:0.013
Epoch: 900,  Cost: 0.000015,  W_0:0.300,  W_1:0.899,  b:0.010
Epoch:1000,  Cost: 0.000008,  W_0:0.300,  W_1:0.899,  b:0.008


In [78]:
hypothesis = torch.matmul(x_train, torch.zeros(size=(2,1), requires_grad=True)) + torch.zeros(size=(1,), requires_grad=True)
mse = torch.mean((hypothesis - y_train) ** 2).item()
print(mse)

42.0
