##### 가장 기초적인 방법의 선형회귀

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 재사용을 위해 랜덤값을 초기화합니다.
torch.manual_seed(2023)    

In [90]:
x_train = torch.FloatTensor([[1,3],[2,6],[3,9]])
y_train = torch.FloatTensor([[3],[6],[9]])

In [91]:
W = torch.zeros(size=(2,1), requires_grad=True)
b = torch.zeros(size=(1,), requires_grad=True)
W, b

(tensor([[0.],
         [0.]], requires_grad=True),
 tensor([0.], requires_grad=True))

In [92]:
hypothesis = torch.matmul(x_train, W) + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [93]:
cost = torch.mean((hypothesis - y_train) ** 2)
optimizer = optim.SGD([W, b], lr=0.01)

In [94]:
nb_epochs = 1000
for epoch in range(nb_epochs+1):
    hypothesis = torch.matmul(x_train, W) + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # cost로 H(x)개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그출력
    if not (epoch % 100) or (epoch % 100 == 99):
        print(f"Epoch:{epoch:4d},  Cost:{cost.item():9.6f},  W_0:{W[0].item():.6f},  W_1:{W[1].item():.6f},  b:{b.item():.6f}")

Epoch:   0,  Cost:42.000000,  W_0:0.280000,  W_1:0.840000,  b:0.120000
Epoch:  99,  Cost: 0.001313,  W_0:0.295890,  W_1:0.887671,  b:0.095607
Epoch: 100,  Cost: 0.001306,  W_0:0.295902,  W_1:0.887705,  b:0.095339
Epoch: 199,  Cost: 0.000749,  W_0:0.296897,  W_1:0.890691,  b:0.072190
Epoch: 200,  Cost: 0.000745,  W_0:0.296905,  W_1:0.890717,  b:0.071988
Epoch: 299,  Cost: 0.000427,  W_0:0.297657,  W_1:0.892971,  b:0.054509
Epoch: 300,  Cost: 0.000424,  W_0:0.297663,  W_1:0.892990,  b:0.054356
Epoch: 399,  Cost: 0.000243,  W_0:0.298231,  W_1:0.894692,  b:0.041158
Epoch: 400,  Cost: 0.000242,  W_0:0.298236,  W_1:0.894707,  b:0.041043
Epoch: 499,  Cost: 0.000139,  W_0:0.298664,  W_1:0.895992,  b:0.031078
Epoch: 500,  Cost: 0.000138,  W_0:0.298668,  W_1:0.896004,  b:0.030990
Epoch: 599,  Cost: 0.000079,  W_0:0.298991,  W_1:0.896974,  b:0.023466
Epoch: 600,  Cost: 0.000079,  W_0:0.298994,  W_1:0.896982,  b:0.023400
Epoch: 699,  Cost: 0.000045,  W_0:0.299238,  W_1:0.897715,  b:0.017718
Epoch:

In [78]:
hypothesis = torch.matmul(x_train, torch.zeros(size=(2,1), requires_grad=True)) + torch.zeros(size=(1,), requires_grad=True)
mse = torch.mean((hypothesis - y_train) ** 2).item()
print(mse)

42.0


In [95]:
hypothesis = torch.matmul(x_train, torch.Tensor([[0.295890],[0.887671]])) + torch.Tensor([0.095607])
mse = torch.mean((hypothesis - y_train) ** 2).item()
print(mse)

0.001305891782976687


In [99]:
print(dir(optimizer))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_cuda_graph_capture_health_check', '_hook_for_profile', '_optimizer_step_code', '_warned_capturable_if_run_uncaptured', '_zero_grad_profile_name', 'add_param_group', 'defaults', 'load_state_dict', 'param_groups', 'state', 'state_dict', 'step', 'zero_grad']


In [108]:
print(optimizer.state)

defaultdict(<class 'dict'>, {tensor([[0.2997],
        [0.8990]], requires_grad=True): {'momentum_buffer': None}, tensor([0.0076], requires_grad=True): {'momentum_buffer': None}})
