##### 가장 기초적인 방법의 선형회귀

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 재사용을 위해 랜덤값을 초기화합니다.
torch.manual_seed(2023)    

In [50]:
x_train = torch.FloatTensor([[1,3],[2,6],[3,9]])
y_train = torch.FloatTensor([[3],[6],[9]])

In [51]:
W = torch.zeros(size=(2,1), requires_grad=True)
b = torch.zeros(size=(1,), requires_grad=True)
W, b

(tensor([[0.],
         [0.]], requires_grad=True),
 tensor([0.], requires_grad=True))

In [52]:
hypothesis = torch.matmul(x_train, W) + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [53]:
cost = torch.mean((hypothesis - y_train) ** 2)
optimizer = optim.SGD([W, b], lr=0.01)

In [54]:
nb_epochs = 1000
for epoch in range(nb_epochs+1):
    hypothesis = torch.matmul(x_train, W) + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # cost로 H(x)개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그출력
    if not (epoch % 100):
        print(f"Epoch:{epoch:4d},  Cost:{cost.item():>2d.6f},  W_0:{W[0].item():.3f},  W_1:{W[1].item():.3f},  b:{b.item():.3f}")

ValueError: Invalid format specifier

In [25]:
a = 13/3
print(f"a:{a:>6.2f}")

a:  4.33
