In [6]:
import torch
import torch.nn as nn

In [3]:
W = torch.tensor(3.0, requires_grad=True)
y = W ** 3 + 2 * W ** 2 + 7

y.backward()
print(f"y를 W로 미분한 값 : {W.grad}")

y를 W로 미분한 값 : 39.0


In [11]:
x = torch.ones(5)   # input tensor
y = torch.zeros(3)  # target tensor
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [12]:
loss.backward()
print(w.grad)
print()
print(b.grad)

tensor([[0.3095, 0.3283, 0.1779],
        [0.3095, 0.3283, 0.1779],
        [0.3095, 0.3283, 0.1779],
        [0.3095, 0.3283, 0.1779],
        [0.3095, 0.3283, 0.1779]])

tensor([0.3095, 0.3283, 0.1779])


In [20]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.MSELoss()(z, y)

In [21]:
loss.backward()
print(w.grad)
print()
print(b.grad)

tensor([[-0.0359, -0.9199,  0.2297],
        [-0.0359, -0.9199,  0.2297],
        [-0.0359, -0.9199,  0.2297],
        [-0.0359, -0.9199,  0.2297],
        [-0.0359, -0.9199,  0.2297]])

tensor([-0.0359, -0.9199,  0.2297])


In [22]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [23]:
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False
