In [2]:
import torch
import torch.nn as nn
import numpy as np

In [24]:
x = [[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]
x = np.array(x)
x = torch.from_numpy(x)
print(x.size())
print()
print(x)

torch.Size([2, 2, 3])

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=torch.int32)


In [14]:
x_flatten = torch.flatten(x)
print(x_flatten)
print(x_flatten.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=torch.int32)
torch.Size([12])


In [16]:
x_Flatten = nn.Flatten()
print(x_Flatten(x))
print(x_Flatten(x).size())

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]], dtype=torch.int32)
torch.Size([2, 6])


In [25]:
y = [[[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]]
y = np.array(x)
y = torch.from_numpy(y)
print(y.size())

print(y)

torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=torch.int32)


In [26]:
y_flatten = torch.flatten(y)
print(y_flatten)
print(y_flatten.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=torch.int32)
torch.Size([12])


In [29]:
y_Flatten = nn.Flatten()
print(y_Flatten(y))
print(y_Flatten(y).shape)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]], dtype=torch.int32)
torch.Size([2, 6])
