In [6]:
import torch
import torch.nn as nn

In [3]:
W = torch.tensor(3.0, requires_grad=True)
y = W ** 3 + 2 * W ** 2 + 7

y.backward()
print(f"y를 W로 미분한 값 : {W.grad}")

y를 W로 미분한 값 : 39.0


In [4]:
x = torch.ones(5)  # 입력 tensor
y = torch.zeros(3)  # 정답 tensor
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [5]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.3116, 0.3142, 0.0904],
        [0.3116, 0.3142, 0.0904],
        [0.3116, 0.3142, 0.0904],
        [0.3116, 0.3142, 0.0904],
        [0.3116, 0.3142, 0.0904]])
tensor([0.3116, 0.3142, 0.0904])


In [7]:
x = torch.ones(5)  # 입력
y = torch.zeros(3)  # 출력

w = torch.randn(5, 3, requires_grad=True) # 가중치
b = torch.randn(3, requires_grad=True) # 편향

z = torch.matmul(x, w) + b
loss_fn = nn.MSELoss() # 손실 함수

In [8]:
loss = loss_fn(z, y)
loss.backward()

print(w.grad)
print(b.grad)

tensor([[ 0.3690,  0.4638, -0.4972],
        [ 0.3690,  0.4638, -0.4972],
        [ 0.3690,  0.4638, -0.4972],
        [ 0.3690,  0.4638, -0.4972],
        [ 0.3690,  0.4638, -0.4972]])
tensor([ 0.3690,  0.4638, -0.4972])


In [9]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [10]:
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False
