In [2]:
import torch
import torch.nn as nn
import numpy as np

In [17]:
x = [[1,2,3],[4,5,6]]
x = np.array(x)
x = torch.from_numpy(x)
print(x.size())
print(x)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [19]:
torch.flatten(x)

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [18]:
flat = nn.Flatten()
flat(x)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)